name: py310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - autopep8=2.0.4=pyhd3eb1b0_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycodestyle=2.12.1=py310h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.17.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.7.2
      - anyio==4.10.0
      - apache-tvm-ffi==0.1.1
      - apscheduler==3.11.0
      - arxiv==2.2.0
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==25.3.0
      - av==15.1.0
      - axial-positional-embedding==0.3.12
      - beautifulsoup4==4.13.5
      - bert-score==0.3.13
      - biopython==1.85
      - bitsandbytes==0.47.0
      - blake3==1.0.7
      - blinker==1.9.0
      - cachetools==5.5.2
      - cbor2==5.7.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - class-registry==2.1.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colt5-attention==0.11.1
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cut-cross-entropy==25.1.1
      - cycler==0.12.1
      - databricks-sdk==0.73.0
      - datasets==3.6.0
      - depyf==0.19.0
      - diffusers==0.35.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docx==0.2.4
      - einops==0.8.1
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - evaluate==0.4.6
      - fastapi==0.118.0
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.2.1
      - fastcore==1.8.13
      - fastrlock==0.8.3
      - fastuuid==0.14.0
      - feedparser==6.0.12
      - ffmpy==0.6.1
      - filelock==3.19.1
      - flash-attn==2.8.3
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.59.1
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - func-timeout==4.3.5
      - future==1.0.0
      - genson==1.3.0
      - gguf==0.17.1
      - ghapi==1.0.8
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.181.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - gpytorch==1.14.3
      - gradio==4.44.1
      - gradio-client==1.3.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - griddataformats==1.0.2
      - grpcio==1.67.1
      - grpcio-status==1.71.2
      - grpclib==0.4.8
      - gunicorn==23.0.0
      - h11==0.16.0
      - h2==4.3.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.8
      - hpack==4.1.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.6.4
      - httpx==0.28.1
      - huey==2.5.4
      - huggingface-hub==1.0.0rc2
      - hyper-connections==0.2.1
      - hyperframe==6.1.0
      - hyperopt==0.2.7
      - identify==2.6.15
      - idna==3.10
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - instructor==1.13.0
      - interegular==0.3.3
      - itsdangerous==2.2.0
      - jaxtyping==0.3.4
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonlines==4.0.0
      - jsonpath-ng==1.7.0
      - jsonpickle==4.1.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - latex2sympy==1.0.3
      - latex2sympy2==1.9.1
      - linear-operator==0.6
      - litellm==1.80.9
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - local-attention==1.11.2
      - loguru==0.7.2
      - lxml==6.0.1
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mda-xdrlib==0.2.0
      - mdanalysis==2.9.0
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - mmtf-python==1.1.3
      - modal==1.2.0
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - narwhals==2.1.2
      - networkx==3.2.1
      - ninja==1.13.0
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.15.0
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.9.79
      - openai==2.11.0
      - openai-harmony==0.0.4
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.3
      - outlines==1.2.9
      - outlines-core==0.2.11
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post6
      - patool==4.0.1
      - peft==0.17.1
      - pfzy==0.3.4
      - pillow==10.4.0
      - plotly==6.3.0
      - ply==3.11
      - pre-commit==4.3.0
      - product-key-memory==0.2.11
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py3dmol==2.5.2
      - py4j==0.10.9.9
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydeck==0.9.1
      - pydub==0.25.1
      - pylatexenc==2.10
      - pymol-open-source-whl==3.1.0.4
      - pyparsing==3.2.3
      - pypdf2==3.0.1
      - python-decouple==3.8
      - python-docx==1.2.0
      - python-dotenv==1.0.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - python-pptx==0.6.23
      - pytube==15.0.0
      - pytz==2025.2
      - pyvis==0.3.2
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - qwen-vl-utils==0.0.11
      - ray==2.49.2
      - referencing==0.36.2
      - reformer-pytorch==1.4.4
      - regex==2023.10.3
      - requests==2.32.5
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - rouge-score==0.1.2
      - rpds-py==0.27.0
      - rsa==4.9.1
      - ruff==0.13.0
      - safetensors==0.6.2
      - scikit-base==0.12.6
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.35.2
      - setproctitle==1.3.7
      - sgmllib3k==1.0.0
      - shap==0.48.0
      - shellingham==1.5.4
      - shortuuid==1.0.11
      - shtab==1.7.2
      - sigtools==4.0.1
      - sktime==0.38.5
      - slicer==0.0.8
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.48.0
      - streamlit==1.48.1
      - streamlit-aggrid==1.1.8.post1
      - swebench==4.1.0
      - sympy==1.13.3
      - synchronicity==0.10.2
      - tabulate==0.9.0
      - tenacity==8.5.0
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - tomlkit==0.12.0
      - torch==2.8.0+cu129
      - torchao==0.12.0
      - torchaudio==2.8.0
      - torchvision==0.23.0+cu129
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.0.dev0
      - triton==3.4.0
      - trl==0.22.1
      - truthtorchlm==0.1.17
      - ty==0.0.1a34
      - typeguard==4.4.4
      - typer==0.17.4
      - typer-slim==0.19.2
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tyro==0.9.28
      - tzdata==2025.2
      - tzlocal==5.3.1
      - unidiff==0.7.5
      - unsloth==2025.8.9
      - unsloth-zoo==2025.8.8
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - virtualenv==20.35.3
      - vllm==0.10.2
      - wadler-lindig==0.1.7
      - wandb==0.21.3
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - websockets==12.0
      - werkzeug==3.1.3
      - wikipedia==1.4.0
      - word2number==1.1
      - xformers==0.0.32.post1
      - xgboost==3.1.2
      - xgrammar==0.1.23
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yarl==1.20.1
